version: '3'
services:
  api-database:
    image: mongo
    container_name: api-database
    ports:
    - 27017:27017
  api:
    image: clientmanager
    container_name: portal
    ports:
    - 9091:8080
    links:
    - api-database